[tool.black]
line-length=79
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
    \.git
  | \.venv
  | migrations
)
'''

[tool.isort]
multi_line_output = 3
line_length = 79
combine_as_imports = true
include_trailing_comma = true

[flake8]
max-line-length=79
